-- AI Decision Firewall - Supabase Database Schema
-- Run this SQL in your Supabase SQL Editor (https://supabase.com/dashboard -> Project -> SQL Editor)

CREATE TABLE IF NOT EXISTS public.action_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type TEXT NOT NULL,
    website TEXT NOT NULL,
    amount NUMERIC NULL,
    risk_level TEXT NOT NULL,
    decision TEXT NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on action_logs
ALTER TABLE public.action_logs ENABLE ROW LEVEL SECURITY;
